In [5]:
# Hello World
## Erin Liang
## uni: ell2147

In [1]:
print('Hello world.')

Hello world.

In [2]:
import sys

print("Python version information:", sys.version_info, "\n")
if sys.version_info.major != 3 or \
    ((sys.version_info.major == 3) and (sys.version_info.minor < 5)):
    print("You have an invalid version of Python.")
else:
    print("Your Python version is OK.")

Python version information: sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)

Your Python version is OK.

In [3]:
python_found = False
anaconda_found = False

for p in sys.path:
    print(p)
    if "anaconda3" in p:
        print("Found anaconda3")
        anaconda_found = True
    if "python" in p:
        print("Found some kind of Python.")
        if not anaconda_found:
            print("Found some type of Python other than Anaconda.")
            print("Test fails")
        else:
            print("OK. Path is good.")
            python_found = True
        break
    
if python_found and anaconda_found:
    print("\nPassed all path tests.")
else:
    print("\nFailed path tests.")

/Users/erinliang/W4111
/Users/erinliang/opt/anaconda3/lib/python37.zip
Found anaconda3
Found some kind of Python.
OK. Path is good.

Passed all path tests.

In [4]:
import conda

In [5]:
conda_version_info =  conda.sys.version_info
print("Your conda version info is\n", conda_version_info)

print("Conda version information:", conda_version_info, "\n")
if conda_version_info.major != 3 or \
    ((conda_version_info.major == 3) and (conda_version_info.minor < 6)):
    print("You have an invalid version of Conda.")
else:
    print("Your Conda version is OK.")

Your conda version info is
 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
Conda version information: sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)

Your Conda version is OK.

In [6]:
import pandas

p_version = pandas.__version__
p_nums = p_version.split(".")

print("Your pandas version is ", p_version)
# modified code from 25 to 1 to pass test (had to update)
if p_nums[1] != '1':
    print("Your version is invalid.")
else:
    print("Your version is OK.")

Your pandas version is  1.1.1
Your version is OK.

In [7]:
print("Professor Ferguson gave us code that accesses a module's property of the form __X__")
ans = input("Answer y or n:")

if ans == 'y' or ans == 'Y':
    print("You failed the test. Prof. Ferguson is too good a programmer to ever do that.")
    print("Reformatting harddrive as punishment.")
elif ans == 'n' or ans == 'N':
    print("You passed the test.")
else:
    print("Really. Answering y or n was too tricky?")

Professor Ferguson gave us code that accesses a module's property of the form __X__
Answer y or n:n
You passed the test.

In [8]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (0.4.0)
Requirement already satisfied: sqlalchemy>=0.6.7 in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython-sql) (1.3.19)
Requirement already satisfied: ipython>=1.0 in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython-sql) (7.18.1)
Requirement already satisfied: prettytable<1 in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython-sql) (0.7.2)
Requirement already satisfied: ipython-genutils>=0.1.0 in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: sqlparse in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython-sql) (0.3.1)
Requirement already satisfied: six in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython-sql) (1.15.0)
Requirement already satisfied: setuptools>=18.5 in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (49.6.0.post20200814)
Requirement already satisfied: traitlets>=4.2 in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.3.3)
Requirement already satisfied: appnope; sys_platform == "darwin" in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.1.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (3.0.7)
Requirement already satisfied: pexpect>4.3; sys_platform != "win32" in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.8.0)
Requirement already satisfied: decorator in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.4.2)
Requirement already satisfied: pygments in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (2.7.0)
Requirement already satisfied: pickleshare in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.7.5)
Requirement already satisfied: jedi>=0.10 in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.14.1)
Requirement already satisfied: backcall in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=1.0->ipython-sql) (0.2.5)
Requirement already satisfied: ptyprocess>=0.5 in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from pexpect>4.3; sys_platform != "win32"->ipython>=1.0->ipython-sql) (0.6.0)
Requirement already satisfied: parso>=0.5.0 in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython>=1.0->ipython-sql) (0.5.2)

In [9]:
%load_ext sql

In [10]:
!pip install PyMySQL # re-ran cell, but initially was uninstalled

Requirement already satisfied: PyMySQL in /Users/erinliang/opt/anaconda3/lib/python3.7/site-packages (0.10.1)

In [11]:
%load_ext sql
%sql mysql+pymysql://root:dbuserdbuser@localhost/w4111

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [12]:
%sql select * from countries;

 * mysql+pymysql://root:***@localhost/w4111
0 rows affected.

[]

In [13]:
import pandas as pd

url="https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
countries=pd.read_csv(url)
countries

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [14]:
countries.rename(columns={"Country": "name", "Region": "region"}, inplace=True)
countries

          name         region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [15]:
import pymysql
from sqlalchemy import create_engine
# changed username from dbuser to root
engine = create_engine('mysql+pymysql://root:dbuserdbuser@localhost/w4111')

In [16]:
# this statement worked if you did not get an error
countries.to_sql(name='countries', con=engine, if_exists='append', index='id');

In [23]:
%sql select * from countries;

 * mysql+pymysql://root:***@localhost/w4111
194 rows affected.

[(0, 'Algeria', 'AFRICA'),
 (1, 'Angola', 'AFRICA'),
 (2, 'Benin', 'AFRICA'),
 (3, 'Botswana', 'AFRICA'),
 (4, 'Burkina', 'AFRICA'),
 (5, 'Burundi', 'AFRICA'),
 (6, 'Cameroon', 'AFRICA'),
 (7, 'Cape Verde', 'AFRICA'),
 (8, 'Central African Republic', 'AFRICA'),
 (9, 'Chad', 'AFRICA'),
 (10, 'Comoros', 'AFRICA'),
 (11, 'Congo', 'AFRICA'),
 (12, 'Congo, Democratic Republic of', 'AFRICA'),
 (13, 'Djibouti', 'AFRICA'),
 (14, 'Egypt', 'AFRICA'),
 (15, 'Equatorial Guinea', 'AFRICA'),
 (16, 'Eritrea', 'AFRICA'),
 (17, 'Ethiopia', 'AFRICA'),
 (18, 'Gabon', 'AFRICA'),
 (19, 'Gambia', 'AFRICA'),
 (20, 'Ghana', 'AFRICA'),
 (21, 'Guinea', 'AFRICA'),
 (22, 'Guinea-Bissau', 'AFRICA'),
 (23, 'Ivory Coast', 'AFRICA'),
 (24, 'Kenya', 'AFRICA'),
 (25, 'Lesotho', 'AFRICA'),
 (26, 'Liberia', 'AFRICA'),
 (27, 'Libya', 'AFRICA'),
 (28, 'Madagascar', 'AFRICA'),
 (29, 'Malawi', 'AFRICA'),
 (30, 'Mali', 'AFRICA'),
 (31, 'Mauritania', 'AFRICA'),
 (32, 'Mauritius', 'AFRICA'),
 (33, 'Morocco', 'AFRICA'),
 (34, 'Mozambique', 'AFRICA'),
 (35, 'Namibia', 'AFRICA'),
 (36, 'Niger', 'AFRICA'),
 (37, 'Nigeria', 'AFRICA'),
 (38, 'Rwanda', 'AFRICA'),
 (39, 'Sao Tome and Principe', 'AFRICA'),
 (40, 'Senegal', 'AFRICA'),
 (41, 'Seychelles', 'AFRICA'),
 (42, 'Sierra Leone', 'AFRICA'),
 (43, 'Somalia', 'AFRICA'),
 (44, 'South Africa', 'AFRICA'),
 (45, 'South Sudan', 'AFRICA'),
 (46, 'Sudan', 'AFRICA'),
 (47, 'Swaziland', 'AFRICA'),
 (48, 'Tanzania', 'AFRICA'),
 (49, 'Togo', 'AFRICA'),
 (50, 'Tunisia', 'AFRICA'),
 (51, 'Uganda', 'AFRICA'),
 (52, 'Zambia', 'AFRICA'),
 (53, 'Zimbabwe', 'AFRICA'),
 (54, 'Afghanistan', 'ASIA'),
 (55, 'Bahrain', 'ASIA'),
 (56, 'Bangladesh', 'ASIA'),
 (57, 'Bhutan', 'ASIA'),
 (58, 'Brunei', 'ASIA'),
 (59, 'Burma', 'ASIA'),
 (60, 'Cambodia', 'ASIA'),
 (61, 'China', 'ASIA'),
 (62, 'East Timor', 'ASIA'),
 (63, 'India', 'ASIA'),
 (64, 'Indonesia', 'ASIA'),
 (65, 'Iran', 'ASIA'),
 (66, 'Iraq', 'ASIA'),
 (67, 'Israel', 'ASIA'),
 (68, 'Japan', 'ASIA'),
 (69, 'Jordan', 'ASIA'),
 (70, 'Kazakhstan', 'ASIA'),
 (71, 'Korea, North', 'ASIA'),
 (72, 'Korea, South', 'ASIA'),
 (73, 'Kuwait', 'ASIA'),
 (74, 'Kyrgyzstan', 'ASIA'),
 (75, 'Laos', 'ASIA'),
 (76, 'Lebanon', 'ASIA'),
 (77, 'Malaysia', 'ASIA'),
 (78, 'Maldives', 'ASIA'),
 (79, 'Mongolia', 'ASIA'),
 (80, 'Nepal', 'ASIA'),
 (81, 'Oman', 'ASIA'),
 (82, 'Pakistan', 'ASIA'),
 (83, 'Philippines', 'ASIA'),
 (84, 'Qatar', 'ASIA'),
 (85, 'Russian Federation', 'ASIA'),
 (86, 'Saudi Arabia', 'ASIA'),
 (87, 'Singapore', 'ASIA'),
 (88, 'Sri Lanka', 'ASIA'),
 (89, 'Syria', 'ASIA'),
 (90, 'Tajikistan', 'ASIA'),
 (91, 'Thailand', 'ASIA'),
 (92, 'Turkey', 'ASIA'),
 (93, 'Turkmenistan', 'ASIA'),
 (94, 'United Arab Emirates', 'ASIA'),
 (95, 'Uzbekistan', 'ASIA'),
 (96, 'Vietnam', 'ASIA'),
 (97, 'Yemen', 'ASIA'),
 (98, 'Albania', 'EUROPE'),
 (99, 'Andorra', 'EUROPE'),
 (100, 'Armenia', 'EUROPE'),
 (101, 'Austria', 'EUROPE'),
 (102, 'Azerbaijan', 'EUROPE'),
 (103, 'Belarus', 'EUROPE'),
 (104, 'Belgium', 'EUROPE'),
 (105, 'Bosnia and Herzegovina', 'EUROPE'),
 (106, 'Bulgaria', 'EUROPE'),
 (107, 'Croatia', 'EUROPE'),
 (108, 'Cyprus', 'EUROPE'),
 (109, 'Czech Republic', 'EUROPE'),
 (110, 'Denmark', 'EUROPE'),
 (111, 'Estonia', 'EUROPE'),
 (112, 'Finland', 'EUROPE'),
 (113, 'France', 'EUROPE'),
 (114, 'Georgia', 'EUROPE'),
 (115, 'Germany', 'EUROPE'),
 (116, 'Greece', 'EUROPE'),
 (117, 'Hungary', 'EUROPE'),
 (118, 'Iceland', 'EUROPE'),
 (119, 'Ireland', 'EUROPE'),
 (120, 'Italy', 'EUROPE'),
 (121, 'Latvia', 'EUROPE'),
 (122, 'Liechtenstein', 'EUROPE'),
 (123, 'Lithuania', 'EUROPE'),
 (124, 'Luxembourg', 'EUROPE'),
 (125, 'Macedonia', 'EUROPE'),
 (126, 'Malta', 'EUROPE'),
 (127, 'Moldova', 'EUROPE'),
 (128, 'Monaco', 'EUROPE'),
 (129, 'Montenegro', 'EUROPE'),
 (130, 'Netherlands', 'EUROPE'),
 (131, 'Norway', 'EUROPE'),
 (132, 'Poland', 'EUROPE'),
 (133, 'Portugal', 'EUROPE'),
 (134, 'Romania', 'EUROPE'),
 (135, 'San Marino', 'EUROPE'),
 (136, 'Serbia', 'EUROPE'),
 (137, 'Slovakia', 'EUROPE'),
 (138, 'Slovenia', 'EUROPE'),
 (139, 'Spain', 'EUROPE'),
 (140, 'Sweden', 'EUROPE'),
 (141, 'Switzerland', 'EUROPE'),
 (142, 'Ukraine', 'EUROPE'),
 (143, 'United Kingdom', 'EUROPE'),
 (144, 'Vatican City', 'EUROPE'),
 (145, 'Antigua and Barbuda', 'NORTH AMERICA'),
 (146, 'Bahamas', 'NORTH AMERICA'),
 (147, 'Barbados', 'NORTH AMERICA'),
 (148, 'Belize', 'NORTH AMERICA'),
 (149, 'Canada', 'NORTH AMERICA'),
 (150, 'Costa Rica', 'NORTH AMERICA'),
 (151, 'Cuba', 'NORTH AMERICA'),
 (152, 'Dominica', 'NORTH AMERICA'),
 (153, 'Dominican Republic', 'NORTH AMERICA'),
 (154, 'El Salvador', 'NORTH AMERICA'),
 (155, 'Grenada', 'NORTH AMERICA'),
 (156, 'Guatemala', 'NORTH AMERICA'),
 (157, 'Haiti', 'NORTH AMERICA'),
 (158, 'Honduras', 'NORTH AMERICA'),
 (159, 'Jamaica', 'NORTH AMERICA'),
 (160, 'Mexico', 'NORTH AMERICA'),
 (161, 'Nicaragua', 'NORTH AMERICA'),
 (162, 'Panama', 'NORTH AMERICA'),
 (163, 'Saint Kitts and Nevis', 'NORTH AMERICA'),
 (164, 'Saint Lucia', 'NORTH AMERICA'),
 (165, 'Saint Vincent and the Grenadines', 'NORTH AMERICA'),
 (166, 'Trinidad and Tobago', 'NORTH AMERICA'),
 (167, 'United States', 'NORTH AMERICA'),
 (168, 'Australia', 'OCEANIA'),
 (169, 'Fiji', 'OCEANIA'),
 (170, 'Kiribati', 'OCEANIA'),
 (171, 'Marshall Islands', 'OCEANIA'),
 (172, 'Micronesia', 'OCEANIA'),
 (173, 'Nauru', 'OCEANIA'),
 (174, 'New Zealand', 'OCEANIA'),
 (175, 'Palau', 'OCEANIA'),
 (176, 'Papua New Guinea', 'OCEANIA'),
 (177, 'Samoa', 'OCEANIA'),
 (178, 'Solomon Islands', 'OCEANIA'),
 (179, 'Tonga', 'OCEANIA'),
 (180, 'Tuvalu', 'OCEANIA'),
 (181, 'Vanuatu', 'OCEANIA'),
 (182, 'Argentina', 'SOUTH AMERICA'),
 (183, 'Bolivia', 'SOUTH AMERICA'),
 (184, 'Brazil', 'SOUTH AMERICA'),
 (185, 'Chile', 'SOUTH AMERICA'),
 (186, 'Colombia', 'SOUTH AMERICA'),
 (187, 'Ecuador', 'SOUTH AMERICA'),
 (188, 'Guyana', 'SOUTH AMERICA'),
 (189, 'Paraguay', 'SOUTH AMERICA'),
 (190, 'Peru', 'SOUTH AMERICA'),
 (191, 'Suriname', 'SOUTH AMERICA'),
 (192, 'Uruguay', 'SOUTH AMERICA'),
 (193, 'Venezuela', 'SOUTH AMERICA')]

In [1]:
# I think that's everything!